# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker BUNDLE from Docker Hub as your build environment.

image: maven:3-eclipse-temurin-17

pipelines:
  default:
      - step:
          name: 'Grab m2'
          cache: maven
          script:
            - BUNDLE="maven-m2"
            - DATE=`date '+%Y%m%d-%H%M'`
            # install deps
            - mvn package -Dmaven.test.skip=true
            - tar -cvzf $BUNDLE-$DATE.tgz -C ~ .m2 
            - ls -alh
            - |
              curl -X POST \
                "https://${BITBUCKET_USERNAME}:${BITBUCKET_APP_PASSWORD}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" \
                --form files=@"$BUNDLE-$DATE.tgz"
          artifacts: # defining the artifacts to be passed to each future step.
           - $BUNDLE-$DATE.tgz

